options:
  logpath:
    type: string
    default: "/var/log/*.log /var/log/*/*.log"
    description: "Space separated log paths to monitor. Can contain wildcards."
  install_sources:
    type: string
    default: deb http://packages.elastic.co/beats/apt stable main
    description: APT repository to fetch filebeat from
  install_keys:
    type: string
    default: D88E42B4
    description: repository key
  harvester_buffer_size:
    type: int
    default: 16384
    description: Defines the buffer size every harvester uses when fetching the file
  max_bytes:
    type: int
    default: 10485760
    description: Maximum number of bytes a single log event can have. Default 10MB
